name: Deploy to PythonAnywhere

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook
        run: |
          curl -f -X POST https://dmikes.eu.pythonanywhere.com/util/update
